stages:
  - clean
  - build
  - test
  - push

variables:
  IMAGE_NAME: xiaoyu_faq
  CONTAINER_NAME: xiaoyu_faq_test
  SRC_FOLDER: /home/faq

clean:
  stage: clean
  script:
    - docker ps -q --filter "name=${CONTAINER_NAME}" | grep -q . && docker rm -f ${CONTAINER_NAME}
  only:
    - master
  tags:
    - aliyun

build:
  stage: build
  script:
    - docker build -t ${IMAGE_NAME}:latest .
  only:
    - master
  tags:
    - aliyun

test:
  stage: test
  script:
    - docker run --name ${CONTAINER_NAME} -v ${CONTAINER_NAME}:/home/AnyQ/build/solr-4.10.3-anyq/example/solr/collection1 -d ${IMAGE_NAME}
    - sleep 40  # wait for program ready
    - docker exec ${CONTAINER_NAME} bash -c "bash ${SRC_FOLDER}/deploy/test_all.sh"
    - docker stop ${CONTAINER_NAME} && docker rm -f ${CONTAINER_NAME}
  only:
    - master
  tags:
    - aliyun

push:
  stage: push
  script:
    - docker tag ${IMAGE_NAME} ${REGISTRY_URL}/${IMAGE_NAME}
    - docker push ${REGISTRY_URL}/${IMAGE_NAME}